Task 15.5
AlnurT/Begin pull request #12
Opened 2021-10-16 17:14 UTC by AlnurT

2021-10-21 12:08 UTC, E1-Bart0 requested changes

2021-10-21 12:08 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_5/task5.py
> +        if list_of_films.count(film) != 0:
У тебя не выполнено задание про ошибку.

Как проверить есть ли элемент в списке? не используя count.

И думаю тут list_of_films лучше использовать как глобальную переменную она тип константа.

2021-11-09 07:10 UTC, E1-Bart0 requested changes

2021-11-09 07:10 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_5/task5.py
> +]
Обычно, то что в глобальном наймспайсе, и такие константы, пишутся заглавными буквами: LIST_OF_FILMS

2021-11-09 07:10 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_5/task5.py
> +def main(list_of_films):
Есть ли тут что-то?)

2021-11-09 07:10 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_5/task5.py
> +            print(f"Фильм {film} добавлен в список любимых")
тут такое дублирование. Подумай как переделать логику. Чтобы было попроще и не дублировалось)

2021-11-09 07:10 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_5/task5.py
> +    print(f"\nСписок любимых фильмов: {favorite_films(list_of_films, my_films)}")
Подсказка к переделыванию логики

2021-11-09 07:10 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_5/test_task5.py
> +    )
Я бы сначала забил бы списки в переменные, а потом бы их вызывал 
```
data = ...
expect = ...
foo(data) == expect
```

2021-11-09 16:06 UTC, AlnurT commented on Basic collections 1 - list/task15_5/task5.py
> +def main(list_of_films):
На пустых строчках - нет

2021-11-09 16:07 UTC, AlnurT commented on Basic collections 1 - list/task15_5/task5.py
> +    ]
Честно говоря, я и не знал о методе проверки элемента в списке через in.

2021-11-09 16:55 UTC, E1-Bart0 requested changes

2021-11-09 16:55 UTC, E1-Bart0 commented on .flake8
> +         N803,  # Argument name should be lowercase
Ты не должен так просто сюда все добавлять)) Что означает, что переменная в глобальном наймспайсе?

2021-11-09 16:55 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_5/task5.py
> +def favorite_films(LIST_OF_FILMS: list, film: str) -> bool:
название тебя не смущает)

2021-11-09 16:55 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_5/task5.py
> +    return film in LIST_OF_FILMS
Какая сложность? Можно ли сделать лучше? Надо почитать про различные коллекции в питоне? Какие вообще есть типы данных? Какие изменяемые? Какие не изменяемые? Что значит, что они не изменяемые?

2021-11-09 16:55 UTC, E1-Bart0 commented on .flake8
> +         N803,  # Argument name should be lowercase
Чем глобальный отличается от локального?

2021-11-10 12:51 UTC, AlnurT commented on .flake8
> +         N803,  # Argument name should be lowercase
Если своими словами, то в глобальном содержатся все объекты, функции и т.д., которые можно использовать везде в коде, они общие для всего кода. Локальные - имеют свои объекты, которые существуют в рамках конкретной функции.

2021-11-10 13:06 UTC, AlnurT commented on Basic collections 1 - list/task15_5/task5.py
> +    return film in LIST_OF_FILMS
Вроде O(N). Кортежи и другое у меня будет в следующих главах, мне сейчас всё изучить? Я вкратце прочитал про коллекции и их особенности.

2021-11-13 12:18 UTC, AlnurT commented on .flake8
> +         N803,  # Argument name should be lowercase
А ещё узнал, если сложные переменные, типо списка, изменяются в функции, то они изменяется в принципе, а не только там.

2021-11-13 12:29 UTC, AlnurT commented on Basic collections 1 - list/task15_5/task5.py
> +    return film in LIST_OF_FILMS
Изменяемые: списки и множества.
Неизменяемые: строки, кортежи и неизм. множества.
Неизменяемые, значит мы не можем менять элементы коллекции (удалять, добавлять и изменять).

2021-11-15 14:54 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_5/task5.py
> +    ]
Ну это самое крутое, что может быть)) Прям английская речь)

2021-11-15 15:04 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_5/task5.py
> +    return film in LIST_OF_FILMS
У тебя по урокам вроде не будет set вообще. Ну я быстро глянул, может упустил. А так ну это просто основные типы лист, кортеж и множество. У множество очень интересная особенность. Проверка наличия элемента во  множестве это O(1). Поэтому она наиболее эффективна в данной ситуации. Я просто долго этого не знал. И когда-то на этом запоролся. Поэтому знай, если у тебя задача проверка на наличие где-то, том можно сделать с использованием set или dict, так как у них O(1)

2021-11-20 13:08 UTC, merged