Task 15.6
AlnurT/Begin pull request #13
Opened 2021-11-09 16:33 UTC by AlnurT

2021-11-09 17:04 UTC, E1-Bart0 requested changes

2021-11-09 17:04 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_6/task15_6.py
> +    return uniqueness
В прошлом задании ты познакомился или познакомишься с новой коллекцией в питоне. Не забывай про нее

2021-11-09 17:04 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_6/task15_6.py
> +def unique_symbols(word: str) -> int:
что такое уникальные символы?

2021-11-09 17:52 UTC, AlnurT commented on Basic collections 1 - list/task15_6/task15_6.py
> +def unique_symbols(word: str) -> int:
Которые не повторяются более 2 раз в слове

2021-11-09 17:52 UTC, AlnurT commented on Basic collections 1 - list/task15_6/task15_6.py
> +    return uniqueness
Новая коллекция?

2021-11-15 15:05 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_6/task15_6.py
> +    return uniqueness
set

2021-11-15 15:07 UTC, E1-Bart0 requested changes

2021-11-15 15:07 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_6/task15_6.py
> +    return uniqueness
Посмотри что такое сет. Это займет минут 5-10. И ты узнаешь как можно сделать это очень легко)

2021-11-27 16:42 UTC, AlnurT commented on Basic collections 1 - list/task15_6/task15_6.py
> +    return uniqueness
Множества же дадут все символы, которые есть в слове, а не символы, которые попадаются в слове 1 раз.

2021-11-27 16:43 UTC, AlnurT commented on Basic collections 1 - list/task15_6/task15_6.py
> +    return uniqueness
Пример: лава
множество даст 3 символа в коллекции, но уникальных же 2.

2021-11-27 18:22 UTC, AlnurT commented on Basic collections 1 - list/task15_6/task15_6.py
> +def unique_symbols(word: str) -> int:
показать их количество

2021-12-03 07:01 UTC, E1-Bart0 requested changes

2021-12-03 07:01 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_6/task15_6.py
> +    return uniqueness
Да, я опять тупанул. Но какая сложность твоего решения? Можно ли сделать быстрее? Ты знаком с dict()?

2021-12-18 17:01 UTC, AlnurT commented on Basic collections 1 - list/task15_6/task15_6.py
> +    return uniqueness
Вроде O(N^2). Да со словарем знаком

2021-12-18 17:30 UTC, AlnurT commented on Basic collections 1 - list/task15_6/task15_6.py
> +    return uniqueness
Через словарь в коде, но можно через все что угодно:
l = [symbol for symbol in a if a.count(symbol) == 1]
len(l)

2021-12-18 17:30 UTC, AlnurT commented on Basic collections 1 - list/task15_6/task15_6.py
> +    return uniqueness
Хотя вроде сложность не уменьшилась

2021-12-23 10:55 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_6/task15_6.py
> +    return uniqueness
Как из вариантов решения посмотри что будет. И попытайся сам реализовать эту логику с использование dict
```
from collections import Counter
word = 'Some words that ...'
print(Counter({' ': 3, '.': 3, 'o': 2, 't': 2, 'S': 1, 'm': 1, 'e': 1, 'w': 1, 'r': 1, 'd': 1, 's': 1, 'h': 1, 'a': 1}))
```
И какая сложность такого решения?

2021-12-25 13:40 UTC, E1-Bart0 approved these changes

2021-12-25 13:42 UTC, merged