Task 15.7
AlnurT/Begin pull request #14
Opened 2021-11-09 16:35 UTC by AlnurT

2021-11-09 17:19 UTC, E1-Bart0 requested changes

2021-11-09 17:19 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_7/task15_7.py
> +        print(f"Вес {count + 1} контейнера: {new_weight_list[count]}")
А зачем заново сортировать. просто вставь в нужное место?
И for не питонячий. Можно проще)

2021-11-09 17:19 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_7/task15_7.py
> +    while count <= number_of_containers:
А зачем вайл?

2021-11-09 17:19 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_7/task15_7.py
> +        print(f"Вес {count + 1} контейнера: {new_weight_list[count]}")
А это мы просто добавляем. Тогда пусть сорт будет, а с фором попроще)

2021-11-09 17:19 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_7/test_task15_7.py
> +
Нет теста где вес больше 200, вводимых контейнеров. Можешь посмотреть как замокать(@patch()) input?

2021-11-09 17:19 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_7/task15_7.py
> +            break
Не знаю есть ли смысл, но можно просто в вайл без ифоф

2021-11-09 17:19 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_7/test_task15_7.py
> +
Еще напишешь тест с путсым списком. Вставит он ли его в список?

2021-11-09 17:56 UTC, AlnurT commented on Basic collections 1 - list/task15_7/task15_7.py
> +        print(f"Вес {count + 1} контейнера: {new_weight_list[count]}")
> А зачем заново сортировать. просто вставь в нужное место? И for не питонячий. Можно проще)

Я решил сделать интереснее, чтобы мы вводили случайный вес, а нам выдавало в виде отсортированного.

2021-11-09 17:57 UTC, AlnurT commented on Basic collections 1 - list/task15_7/task15_7.py
> +        print(f"Вес {count + 1} контейнера: {new_weight_list[count]}")
> А это мы просто добавляем. Тогда пусть сорт будет, а с фором попроще)

Не понял.

2021-11-09 17:57 UTC, AlnurT commented on Basic collections 1 - list/task15_7/task15_7.py
> +    while count <= number_of_containers:
Чтобы сравнивать не все элементы, а только до определенного

2021-11-09 18:02 UTC, AlnurT commented on Basic collections 1 - list/task15_7/task15_7.py
> +            break
Я это сделал для корректной работы цикла, если новый контейнер будет в конце.

2021-11-15 15:17 UTC, E1-Bart0 requested changes

2021-11-15 15:17 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_7/task15_7.py
> +    while new_weight <= new_weight_list[count - 1]:
Молодец. Давай еще практиковаться. Подумай как сделать с for

2021-11-15 15:17 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_7/task15_7.py
> +    while new_weight <= new_weight_list[count - 1]:
Тяжело в учение, потом будет проще))

2021-11-15 15:17 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_7/test_task15_7.py
> +
Хуйню написал, Там из условия этого не может быть, Но на звездочку можешь сделать)

2021-11-15 15:17 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_7/task15_7.py
> +        print(f"Вес {count + 1} контейнера: {new_weight_list[count]}")
enumerate

2021-12-03 07:05 UTC, E1-Bart0 commented
CI не прошел. У тебя наверно пре-коммит сломался. Ты же переделывал что-то. Либо руками
```
$ black .
$ isort .
$ flake8 .
$ mypy .
```
Либо попробуй починить пре-коммит. Там в makefile посмотри. Вроде должно быть что-то

2021-12-03 07:19 UTC, E1-Bart0 approved these changes

2021-12-03 07:19 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_7/task15_7.py
> +    return len(sorted_weight_list) + 1
да. Куда лучше=). Но можно поправить:
for index, container_weight in enumerate():

2021-12-03 07:19 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_7/task15_7.py
> +        print(f"Вес {container[0] + 1} контейнера: {container[1]}")
так же enumerate можно на индекс и что-то

2021-12-03 07:19 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_7/task15_7.py
> +        f"Номер, куда встанет новый контейнер: {show_number_of_new_container(sorted_weight_list, new_weight)}"
Вынеси в отдельную переменную show_number_of_new_container(sorted_weight_list, new_weight)

2021-12-03 07:19 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_7/task15_7.py
> +    return weight_list
ты эту штуку один раз используешь. не думаю что имеет смысл так сильно дробить. Ты как бы вызываешь метод просто. Ну если так больше нравиться ,то можешь_)

2021-12-18 18:12 UTC, AlnurT commented
> CI не прошел. У тебя наверно пре-коммит сломался. Ты же переделывал что-то. Либо руками
> 
> ```
> $ black .
> $ isort .
> $ flake8 .
> $ mypy .
> ```
> 
> Либо попробуй починить пре-коммит. Там в makefile посмотри. Вроде должно быть что-то

2021-12-18 18:13 UTC, AlnurT commented
Какой makefile?

2021-12-26 18:39 UTC, merged