Task 15.8
AlnurT/Begin pull request #15
Opened 2021-11-09 16:35 UTC by AlnurT

2021-11-09 17:27 UTC, E1-Bart0 requested changes

2021-11-09 17:27 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_8/task15_8.py
> +            listt.insert(0, listt[len(listt) - 1])
listt[len(listt) - 1])
Ты хочешь получить последний элемент из списка? Как можно

2021-11-09 17:27 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_8/task15_8.py
> +            listt.pop()
Потренируйся со слайсами еще)  Попроще будет решение)

2021-11-27 16:19 UTC, AlnurT commented
Походу из-за новой версии питона нужно что-то поменять в линтерах?

2021-12-03 07:41 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_8/task15_8.py
> +        print(f"Введите {_ + 1} элемент списка: ", end="")
если переменная _  то она буферная, тип вообще не используется. Если ее используешь, то лучше дать ей имя

2021-12-03 07:41 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_8/task15_8.py
> +    return listt[-(len(listt) - shift):] + listt[:shift]
Что-то странно вроде. В вк написал

2021-12-03 07:42 UTC, E1-Bart0 commented
CI не прошел. Попробуй python 3.10.0

2021-12-26 17:29 UTC, AlnurT commented
Урааааа, я разобрался с ручной установкой пакетов

2021-12-26 18:39 UTC, merged