Task 16.9
AlnurT/Begin pull request #25
Opened 2022-01-13 16:41 UTC by AlnurT

2022-01-13 17:23 UTC, E1-Bart0 requested changes

2022-01-13 17:23 UTC, E1-Bart0 commented on Methods for working with lists/task16_9/task16_9.py
> +    dict_of_debt = dict.fromkeys(range(1, num_of_friends + 1), 0)
Можешь использовать defaultdict
from collections import defaultdict

2022-01-18 13:31 UTC, AlnurT commented on Methods for working with lists/task16_9/task16_9.py
> +    dict_of_debt = dict.fromkeys(range(1, num_of_friends + 1), 0)
Нам же тогда придётся дополнительно сортировать словарь по ключам, иначе у нас номера друзей в всегда будут в рандомном порядке. Типо: {2: 100, 1: 200, 3: -300}

2022-01-28 18:24 UTC, E1-Bart0 requested changes

2022-01-28 18:24 UTC, E1-Bart0 commented on Methods for working with lists/task16_9/task16_9.py
> +    dict_of_debt = dict.fromkeys(range(1, num_of_friends + 1), 0)
Не понял, ну и что, что они не упорядочены?
Попробуй использовать defaultdict. Ты с ним не знаком. И у него немного странный синтаксис, я долго не мог въехать

2022-01-30 12:58 UTC, AlnurT commented on Methods for working with lists/task16_9/task16_9.py
> +    dict_of_debt = dict.fromkeys(range(1, num_of_friends + 1), 0)
ок, попробую, просто оно так некрасиво выглядит)

2022-05-14 16:49 UTC, E1-Bart0 approved these changes

2022-05-30 13:23 UTC, closed without merging