Task 16.10
AlnurT/Begin pull request #26
Opened 2022-01-13 17:32 UTC by AlnurT

2022-01-14 15:03 UTC, E1-Bart0 requested changes

2022-01-14 15:03 UTC, E1-Bart0 commented on Methods for working with lists/task16_10/task16_10.py
> +        list_numbers.insert(insert_index, num)
I like this. Very smart

2022-01-14 15:03 UTC, E1-Bart0 commented on Methods for working with lists/task16_10/task16_10.py
> +    for num in list_numbers:
It's when you iterate through a list and add elements to the list it's better to iterate through a copy
like for _ in list.copy()

2022-01-20 11:11 UTC, AlnurT commented on Methods for working with lists/task16_10/task16_10.py
> +    list_new_numbers = assign_numbers_for_list_symmetry(list_numbers, [])[1]
2 times. I`ve already corected.

2022-01-20 11:20 UTC, AlnurT commented on Methods for working with lists/task16_10/task16_10.py
> +    for num in list_numbers:
In order not to damage the list or why?

2022-01-28 18:26 UTC, E1-Bart0 approved these changes

2022-01-28 18:26 UTC, E1-Bart0 commented on Methods for working with lists/task16_10/test_task16_10.py
> +    assert assign_numbers_for_list_symmetry([1, 3, 3, 1]) == ([])
== ([]) Что это значит?

2022-01-28 18:29 UTC, E1-Bart0 approved these changes

2022-01-30 13:04 UTC, AlnurT commented on Methods for working with lists/task16_10/test_task16_10.py
> +    assert assign_numbers_for_list_symmetry([1, 3, 3, 1]) == ([])
По ошибке оставил скобки

2022-01-30 13:04 UTC, merged