Task 17.5
AlnurT/Begin pull request #30
Opened 2022-01-28 16:29 UTC by AlnurT

2022-01-28 18:44 UTC, E1-Bart0 requested changes

2022-01-28 18:44 UTC, E1-Bart0 commented on List comprehensions/task17_5/task17_5.py
> +    return random_string[right_border:left_border:-1]
Окей) ]придумаешь еще способ это сделать. Можно в комментах тут

2022-01-28 18:44 UTC, E1-Bart0 commented on List comprehensions/task17_5/test_task17_5.py
> +)
Ой, хорошо, что параметризовал

2022-02-22 12:13 UTC, AlnurT commented on List comprehensions/task17_5/task17_5.py
> +    return random_string[right_border:left_border:-1]
У меня есть куча способов через for и while, но в них большой код + больше времени выполнения требуют.

2022-02-22 12:18 UTC, AlnurT commented on List comprehensions/task17_5/task17_5.py
> +    return random_string[right_border:left_border:-1]
Есть вариант со сплитом, но там тяжко если символ встречается больше 2 раз.

2022-02-22 12:25 UTC, AlnurT commented on List comprehensions/task17_5/task17_5.py
> +    return random_string[right_border:left_border:-1]
Можно через replace, но опять проблема в количестве повторений.

2022-02-22 12:30 UTC, AlnurT commented on List comprehensions/task17_5/task17_5.py
> +    return random_string[right_border:left_border:-1]
Вроде так можно:
random_string = random_string.replace(symbol, '', 1)[::-1]
random_string = random_string.replace(symbol, '', 1)

2022-02-22 12:36 UTC, AlnurT commented on List comprehensions/task17_5/task17_5.py
> +    return random_string[right_border:left_border:-1]
Но это работает, если наш символ в начале и в конце

2022-05-14 16:59 UTC, E1-Bart0 approved these changes

2022-05-30 13:34 UTC, closed without merging