Initial Task 15.3
AlnurT/Begin pull request #8
Opened 2021-10-16 17:13 UTC by AlnurT

2021-10-21 11:35 UTC, E1-Bart0 requested changes

2021-10-21 11:35 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_3/task3.py
> +    return low_efficiency
Привет)
List comprehensive ты де еще не проходил?
Тогда посмотри что такое enumerate(), list.join() и самое главное list.filter()

2021-10-21 11:35 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_3/test_task3.py
> +    assert cell_selection(5, [3, 0, 6, 2, 10]) == "0 2 "
В конце пробел, как-то странно) Но join() должен будет решить эту проблему))

2021-10-21 11:37 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_3/task3.py
> +    return low_efficiency
filter как и map работает, создает генератор)

2021-11-09 06:50 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_3/task3.py
> +    ]
Молодец👍  Потренируемся), напишешь через filter(). С фильтром лучше использовать не range. Как еще можно получить индексы элементов

2021-11-09 15:15 UTC, AlnurT commented on Basic collections 1 - list/task15_3/task3.py
> +    ]
Через list.index определенного элемента списка.

2021-11-09 16:47 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_3/task3.py
> +    ]
Знаешь что такое enumerate?

2021-11-09 16:50 UTC, E1-Bart0 commented
Знаешь что такое enumerate?

2021-11-09 17:47 UTC, AlnurT commented on Basic collections 1 - list/task15_3/task3.py
> +    ]
Не, я же до кортежей не дошел ещё.

2021-11-10 12:42 UTC, AlnurT commented on Basic collections 1 - list/task15_3/task3.py
> +    ]
Но вроде понял про enumerate

2021-11-13 12:16 UTC, AlnurT commented
> Знаешь что такое enumerate?

Что-то типо range, только помимо индекса элемента, позволяет получить кортеж из индекса и самого элемента.

2021-11-15 14:49 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_3/task3.py
> +    ]
Так попробуешь сделать с filter(..., enumerate(list))?

2021-11-25 10:03 UTC, AlnurT commented on Basic collections 1 - list/task15_3/task3.py
> +    ]
Если мы так сделаем, мы же сделаем список из кортежей, а оттуда фиг быстро вытащишь элементы.

2021-11-25 10:08 UTC, AlnurT commented on Basic collections 1 - list/task15_3/task3.py
> +    ]
Либо я не знаю как брать каждый 2 элемент всех кортежей внутри списка без использования for.

2021-11-25 10:29 UTC, AlnurT commented on Basic collections 1 - list/task15_3/task3.py
> +    ]
low_efficiency = [low[1] for low in filter(lambda eff: eff[1] < eff[0], enumerate(efficiency))]

2021-11-25 10:32 UTC, AlnurT commented on Basic collections 1 - list/task15_3/task3.py
> +    ]
Легче этого: low_efficiency = filter(lambda eff: eff < efficiency.index(eff), efficiency)
не получилось

2021-12-03 06:48 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_3/task3.py
> +    ]
Да, все отлично. Я тоже затупил. Ну ты хоть потренился. Я бы использовал все-таки enumerate, но в list comprehensive:
```
[x for index, x in enumerate(a) if index < x]
```
Ты же знал что в for можно сразу расчленить как бы на index и x?
Тип enumerate дает кортеж (0, 0) и мы его в index, x переделываем,

Просто попробуй сделать также, чтобы каждый элемент в переменную засунуть (переменные: f, s, t) для такого массива:
```
a = [(1, (2, 3)), (2, (3, 4))]
lst = [(f, s, t) for ... in a]
print(lst)

### Подсказка. Подумай как это происходит. И что надо добавить, чтобы работало ###
f, s, t = (1, (2, 3))

```

2021-12-03 06:49 UTC, E1-Bart0 approved these changes

2021-12-18 16:49 UTC, AlnurT commented on Basic collections 1 - list/task15_3/task3.py
> +    ]
lst = [(f, s, t) for f, (s, t) in a] 
Типо такого?
Или я не понял

2021-12-23 10:50 UTC, E1-Bart0 commented on Basic collections 1 - list/task15_3/task3.py
> +    ]
Да, все верно =)
Ты понял, почему так нужны дополнительные скобки  f, (s, t)?
Еще можно упомянуть про. Не знаю проходил ты или нет *args и **kwargs. Но к распаковке сюда тоже можно:
```
f, s, *t = (1, 2, 3, 4, 5, 6)
f, *s, t = (1, 2, 3, 4, 5, 6)
```

2021-12-26 16:48 UTC, AlnurT commented on Basic collections 1 - list/task15_3/task3.py
> +    ]
Да, понял: это 2 элемента, второй из которых является кортежем  из 2 элементов.
Получается в первом случае: f = 1, s = 2, t = [3, 4, 5, 6]
Во втором: f = 1, s = [2, 3, 4, 5], t = 6

2021-12-26 16:50 UTC, AlnurT commented on Basic collections 1 - list/task15_3/task3.py
> +    ]
*args это распаковка вложенных элементов
**kwargs - распаковка вложенного словаря

2021-12-26 18:38 UTC, merged